#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    May 07, 2018 10:48:37 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

sys.path.append('..')
import gedcom_parser_support
from gedcom_xml_parser.gedcom_xml_parser import GedcomXMLParser

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    gedcom_parser_support.set_Tk_var()
    top = GEDCOM_PARSER (root)
    gedcom_parser_support.init(root, top)
    root.mainloop()

w = None
def create_GEDCOM_PARSER(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    gedcom_parser_support.set_Tk_var()
    top = GEDCOM_PARSER (w)
    gedcom_parser_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_GEDCOM_PARSER():
    global w
    w.destroy()
    w = None


class GEDCOM_PARSER:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("960x640+204+33")
        top.title("GEDCOM PARSER")
        top.configure(background="#d9d9d9")

        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.06, relheight=0.94, relwidth=0.5)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=475)

        self.GedcomText = ScrolledText(self.Frame1)
        self.GedcomText.place(relx=0.02, rely=0.07, relheight=0.9
                , relwidth=0.95)
        self.GedcomText.configure(background="white")
        self.GedcomText.configure(font="TkTextFont")
        self.GedcomText.configure(foreground="black")
        self.GedcomText.configure(highlightbackground="#d9d9d9")
        self.GedcomText.configure(highlightcolor="black")
        self.GedcomText.configure(insertbackground="black")
        self.GedcomText.configure(insertborderwidth="3")
        self.GedcomText.configure(selectbackground="#c4c4c4")
        self.GedcomText.configure(selectforeground="black")
        self.GedcomText.configure(width=10)
        self.GedcomText.configure(wrap=WORD)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.02, rely=0.02, height=21, width=400)
        self.Label1.configure(anchor=W)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Paste GEDCOM File Text Here''')
        self.Label1.configure(width=444)

        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.5, rely=0.06, relheight=0.94, relwidth=0.5)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(width=125)

        self.XMLText = ScrolledText(self.Frame2)
        self.XMLText.place(relx=0.02, rely=0.07, relheight=0.9
                , relwidth=0.95)
        self.XMLText.configure(background="white")
        self.XMLText.configure(font="TkTextFont")
        self.XMLText.configure(foreground="black")
        self.XMLText.configure(highlightbackground="#d9d9d9")
        self.XMLText.configure(highlightcolor="black")
        self.XMLText.configure(insertbackground="black")
        self.XMLText.configure(insertborderwidth="3")
        self.XMLText.configure(selectbackground="#c4c4c4")
        self.XMLText.configure(selectforeground="black")
        self.XMLText.configure(width=10)
        self.XMLText.configure(wrap=WORD)

        self.Label2 = Label(self.Frame2)
        self.Label2.place(relx=0.02, rely=0.02, height=21, width=400)
        self.Label2.configure(anchor=W)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Parsed XML Will Appear Here''')

        self.Frame3 = Frame(top)
        self.Frame3.place(relx=0.0, rely=0.0, relheight=0.06, relwidth=1.0)
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(background="#d9d9d9")
        self.Frame3.configure(width=955)

        self.Label3 = Label(self.Frame3)
        self.Label3.place(relx=0.01, rely=0.25, height=21, width=450)
        self.Label3.configure(anchor=W)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''GEDCOM -> XML PARSER''')

        self.Button1 = Button(self.Frame3, command=self.parse_text)
        self.Button1.place(relx=0.91, rely=0.2, height=24, width=67)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Parse''')
        self.Button1.configure(width=70)

        self.checkbutton1state = IntVar()
        self.Checkbutton1 = Checkbutton(self.Frame3)
        self.Checkbutton1.place(relx=0.8, rely=0.2, relheight=0.63, relwidth=0.1)

        self.Checkbutton1.configure(activebackground="#d9d9d9")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(background="#d9d9d9")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify=LEFT)
        self.Checkbutton1.configure(text='''Minified XML''')
        self.Checkbutton1.configure(variable=self.checkbutton1state)
        self.Checkbutton1.configure(width=99)

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

    def parse_text(self):
        unparsed_text = self.GedcomText.get(1.0, END)
        parser = GedcomXMLParser(unparsed_text)
        parse_text = parser.get_parsed_data()
        
        if self.checkbutton1state.get() == 1:
            parse_text = parser.get_parsed_data_minified()
        
        self.XMLText.delete('1.0', END)
        self.XMLText.insert(INSERT, parse_text)


# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = Pack.__dict__.keys() | Grid.__dict__.keys() \
                  | Place.__dict__.keys()
        else:
            methods = Pack.__dict__.keys() + Grid.__dict__.keys() \
                  + Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

if __name__ == '__main__':
    vp_start_gui()


